### ISSUE TITLE
Install location

### ISSUE THREAD

**Issue by dfangx** [filips123/FirefoxPWA#17]
Is it possible to change the install location? My understanding is that `/usr/` really should be for system-installed packages, not packages manually installed by the user. Proper install location should be in `/usr/local/*` or in a directory owned by the user.

**Comment by filips123** [comment]
I decided to use `/usr` because I will probably release the package to some package repo (probably PPA or some third-party) where I think packages should be installed directly in `/usr`, and I didn't want to create multiple packages and instructions with multiple install locations.

I might add support for easier changing of install location in the future, but I'm not sure what's the best way to do that.

However, you can change the install location of you build the package from the source:

1. Change directory and file locations in the Rust source code:

   * https://github.com/filips123/FirefoxPWA/blob/4bacdcf47ece8a01856ff1f6b828ee686548bac4/native/src/directories.rs#L27
   * https://github.com/filips123/FirefoxPWA/blob/8d8adb87ddbc078a56d17ba08fd46f90acf0215e/native/src/integrations/linux.rs#L181
   * https://github.com/filips123/FirefoxPWA/blob/8d8adb87ddbc078a56d17ba08fd46f90acf0215e/native/src/integrations/linux.rs#L202

2. Change the location of `firefoxpwa-connector` in the native app manifest:

   * https://github.com/filips123/FirefoxPWA/blob/8d8adb87ddbc078a56d17ba08fd46f90acf0215e/native/manifests/linux.json#L4

3. Either manually copy [listed in README](https://github.com/filips123/FirefoxPWA/tree/8d8adb87ddbc078a56d17ba08fd46f90acf0215e/native#other-linux) to their new locations or [modify `Cargo.toml`](https://github.com/filips123/FirefoxPWA/blob/8d8adb87ddbc078a56d17ba08fd46f90acf0215e/native/Cargo.toml#L69-L90) and build and install DEB package.

   **Important:** You must not change the location of manifest files because Firefox expects them to be in a pre-defined location.

**Comment by dfangx** [comment]
Thanks for the help (and for doing such a great project!). 

Have you considered setting the install prefix with an environment variable? Something like this:

```
        let install = if let Some(prefix) = option_env!("FFPWA_PREFIX") {
            PathBuf::from(prefix)
        }
        else {
            PathBuf::from("/usr/)
        };
```

Then you can still use `/usr/` as the default location and if another install location is wanted, the user can just specify it as an env variable.

Just a thought off the top of my head

**Comment by filips123** [comment]
This could partly work, but the remaining problem is the manifest which still links to the original path. Maybe I could do some `configure`-style script that automatically renames all required paths in the code and manifest or even changes the install instructions in readme.

**Comment by TheFooI** [comment]
Hey, any way to change `/usr/libexec/firefoxpwa-connector` to `/usr/lib/firefoxpwa/firefoxpwa-connector`? [According to the Arch wiki](https://wiki.archlinux.org/title/Arch_packaging_standards#Package_etiquette), that is the way to go. Sorry if that is stupid to ask, I'm still learning about compiling and packaging, which is why I found it.

**Comment by dfangx** [comment]
>This could partly work, but the remaining problem is the manifest which still links to the original path. Maybe I could do some configure-style script that automatically renames all required paths in the code and manifest or even changes the install instructions in readme.

If using an environment variable, you could just ignore it when setting the manifest path and default to the hardcoded path, since it seems like that can't be changed.

**Comment by dfangx** [comment]
@TheFooI maybe try using `sed` to replace the source code paths to the one you want?

**Comment by filips123** [comment]
I made it easier to configure most install locations in https://github.com/filips123/FirefoxPWA/commit/df05306fae01916834575d9d6bd5e371a68ee919. You still need to use `sed` or manually replace the source code, as using build-time env vars could complicate code and make some things harder (for example, using home directory as a path), but I documented what each directory is for, and added [a quick example how (and where) paths can be changed](https://github.com/filips123/FirefoxPWA/blob/df05306fae01916834575d9d6bd5e371a68ee919/native/src/directories.rs#L101-L106). I will also update the wiki with more details about this change.

**Comment by dfangx** [comment]
Is there a plan to do this without having to modify the source code eventually?

**Comment by filips123** [comment]
Yes. I have some idea how to handle home directories, but I first need to check if it works, and do some other things. If it works, I will probably add it in the next release.

**Comment by filips123** [comment]
I implemented support for changing most install locations using build-time environment variables (`FFPWA_EXECUTABLES`, `FFPWA_SYSDATA`, `FFPWA_USERDATA`). However, you will still need to manually edit the installation script and manifest to actually install files to the correct location. This probably can't be changed.

If the variable starts with `~/`, it will be expanded to the user home directory at the run-time.
