### ISSUE TITLE
Can't add 9anime.to to FirefoxPWA

### ISSUE THREAD

**Issue by pc-v2** [filips123/FirefoxPWA#21]
![image](https://user-images.githubusercontent.com/58063311/124594014-80ef8a00-de89-11eb-98b6-0cd91645da45.png)

**Comment by filips123** [comment]
That site uses some "cookie protection" that requires the client to first execute some JavaScript to set a cookie and make another request with that cookie. Unfortunately, FirefoxPWA client can't determine that cookie easily so the request will always fail and return a broken manifest.

When I implement support for installing non-PWA sites, I will also add a switch to force disable manifest usage, so that could be a workaround for installing this site.

**Comment by ThatOneCalculator** [comment]
I know it's not a solution but 4anime.to is honestly better than 9anime.

**Comment by filips123** [comment]
You will be able to uncheck "Use the manifest for determining app properties" when installing this site in the next release.
