### ISSUE TITLE
Add instructions for unofficial AUR package for Arch Linux

### ISSUE THREAD

**Issue by PeterCxy** [filips123/FirefoxPWA#25]
I have packaged the native component for Arch Linux as an [AUR package](https://aur.archlinux.org/packages/firefox-pwa/) for ease of installation on Arch Linux. I understand that linking to an unofficial package in the official instructions may be inappropriate, but it would be nice if something like an "unofficial packages" section in the setup wizard can be added for third-party packages like this one.

**Comment by filips123** [comment]
I will add it to install options along with other install improvements and packages for other distros. Unfortunately, I won't have much time in the following days, and I first need to research Linux packages a bit. This may take some time, but it will probably be ready this month. Until then, I will link the package [in the wiki](https://github.com/filips123/FirefoxPWA/wiki/Installing).

Also, would it be possible to transfer the ownership to me (once I set up an AUR account and learn how to publish packages...), so I could mark it as official and publish new versions as soon as they are released?

**Comment by black7375** [comment]
`.deb` file can also be used at AUR.
It's not that difficult.

Example
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=enpass-bin
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=spotify

AUR related action also exist.
- https://github.com/marketplace/actions/publish-aur-package

**Comment by PeterCxy** [comment]
@filips123 Yes, I can transfer the package to you if you want. AUR "packages" are just build scripts, so it should be relatively easy to get started.

@black7375 I prefer to make the non-`-bin` packages really non-binary (built from source). You can create a separate `firefox-pwa-bin` if you want to use that.

**Comment by filips123** [comment]
I have now made AUR account and researched how AUR packages work.

I made [example PKGBUILD files](https://gist.github.com/filips123/636b337ae7740657bd163167b7e1ef6a) (with `$VERSION` being replaced with an actual version) for both source (from release source) and binary (from DEB archive) packages. They are mostly based on the original `firefox-pwa` PKGBUILD, but I edited them a bit and make them also install READMEs as documentation. I tested them and they seem to build correctly (however, they rely on some things that I will release in the next FirefoxPWA version). Do you think they are fine?

@PeterCxy Can you add me (AUR username filips) as a maintainer or transfer the ownership so I will be able to publish new versions when they are created?

Currently, I plan to manually publish new versions, but I might use that AUR action or somehow otherwise automate publishing in the future.

**Comment by PeterCxy** [comment]
Sure, I'll add you as maintainer once I am home. I'll also synchronize your additions to the package while I do that.

**Comment by PeterCxy** [comment]
@filips123 I've added your AUR account as a co-maintainer for the `firefox-pwa` package.

As a side note, please don't skip the checksums in your PKGBUILDs. It's easy to keep the checksums up to date -- just a `updpkgsums` every time you update the version number.

Also note that my current version of the PKGBUILD has the runtime directory moved to `~/.local/share/firefoxpwa/runtime` (though it seems that the next release will have this path moved to user directory by default).

**Comment by filips123** [comment]
Thanks. I will update checksums when I update version. Next version is now ready, so I will soon release it and also update AUR packages.

**Comment by filips123** [comment]
I uploaded `firefox-pwa` and `firefox-pwa-bin` for 0.5.0 and they seem to work, so I will close this issue.
