### ISSUE TITLE
`openOutOfScopeInDefaultBrowser` (probably) should imply `linksTarget = 2` (open links in new window)

### ISSUE THREAD

**Issue by PeterCxy** [filips123/FirefoxPWA#27]
When the option for opening links in default browser is checked, the behavior is to close the PWA window when the default browser is invoked. This can be quite annoying for apps such as instant messengers and social networks. However, when `linksTarget` is set to 2, forcing links to open in a new window, only the new window is closed and the original PWA window is kept. This might be a better default than opening the links in the current window (when `openOutOfScopeInDefaultBrowser` is set, that is).

**Comment by filips123** [comment]
Yes, that's good idea. I could probably also add an option to open only external URLs in new windows.

**Comment by pc-v2** [comment]
could there be right clicking link to open default browser without enabling out of scope? Proton Mail do open default browser window while launching it at startup, with open out of scope default window enabled.

**Comment by filips123** [comment]
> I could probably also add an option to open only external URLs in new windows.

Actually, I cannot do this so easily, because `browser.link.open_newwindow` is static for all URLs and it is hard to manually interject every link on websites and check where should it open. I may do this in the future, but it is currently not planned.


> However, when `linksTarget` is set to 2, forcing links to open in a new window, only the new window is closed and the original PWA window is kept. This might be a better default than opening the links in the current window (when `openOutOfScopeInDefaultBrowser` is set, that is).

@PeterCxy I will make that switching `openOutOfScopeInDefaultBrowser` from Firefox settings page will set `linksTarget`'s value. Users can still change it later if they want. However, this only applies to the Firefox settings page and not to changes made in `about:config`.

> could there be right clicking link to open default browser without enabling out of scope?

@pc-v2 I will add this in the next version.
