### ISSUE TITLE
Disable server-side decorations by default on Linux

### ISSUE THREAD

**Issue by PeterCxy** [filips123/FirefoxPWA#29]
On Linux (w/ Xorg), Firefox seems to still default to server-side decorations (titlebar), which looks not great with PWA. It's trivial to make it use client-side decorations just like on Windows and macOS by unchecking "Titlebar" in Settings Menu -> More Tools -> Customize Toolbar, but this is not obvious for new users. I'm not sure if it's a good idea or if it's easy to implement, but unsetting this option by default seems to improve the out-of-the-box visuals quite a bit, and it seems to work just fine with Firefox stable at least on my latest KDE installation.

**Comment by filips123** [comment]
Sorry for the late reply. Which problems exactly happen to you when using server-side decorations? I think using them should provide a better user experience overall (because there is just one bar instead of two, so browser UI takes less space and website content can take more), so I would rather try to fix the problems instead of completely disabling server-side decorations.

**Comment by black7375** [comment]
Before
![image](https://user-images.githubusercontent.com/25581533/126068608-ac568dc4-9f14-4999-8e95-e67ad01e520e.png)

After
![image](https://user-images.githubusercontent.com/25581533/126068693-c04df9b5-5a46-49fb-96ff-dde70a4d4aad.png)

Set `user.js` at `https://github.com/filips123/FirefoxPWA/tree/main/native/userchrome/profile/chrome`
- `browser.tabs.drawInTitlebar` to `true`

This is a simple option to set default values ​​for settings.

**Comment by PeterCxy** [comment]
@filips123 Server-side decorations gets you two bars, and disabling it gets you one (as can be seen form the screenshot provided by @black7375). I think disabling it provides the better user experience.

**Comment by filips123** [comment]
Oh, I misunderstood you that you want a separate titlebar instead of disabling/merging it. Yes, I agree that disabling titlebar is better.

It seems that client-side decorations depend on specific Linux distro/desktop environment (for example, on Ubuntu titlebar is hidden by default, and on Linux Mint it is shown). I don't know why this is the case, so I might need to check if disabling titlebar on distros where it is enabled by default causes any unintended problems.

**Comment by black7375** [comment]
As far as I know it depends on the DE.
I am a KDE user and I have not experienced any special problems.

**Comment by PeterCxy** [comment]
@filips123 I believe client-side decorations is just disabled by default on Xorg. Ubuntu uses GNOME, which defaults to Wayland, so that's why CSD is enabled by default.

**Comment by filips123** [comment]
Do you know why they are disabled by default on Xorg? Is it just some convention or to prevent visual problems?

**Comment by PeterCxy** [comment]
I believe there once were issues with CSD on Xorg on KDE, but it's been fixed since quite some time ago (and the issue wasn't really catastrophic to begin with, it was just missing window shadow). I'm not sure about other desktop environments, though.
