### ISSUE TITLE
Option to disable the title bar on Linux

### ISSUE THREAD

**Issue by CRISPYricePC** [filips123/FirefoxPWA#49]
Some window managers on Linux benefit from no client-side decorations

It would be nice to provide an option that would let us disable the title bar if we need

**Comment by filips123** [comment]
You can disable title bar using built-in Firefox Customize page (application menu -> more tools -> customize toolbar -> (un)check title bar). If the title bar option is not shown for you, maybe Firefox does not support your DE/WM. In this case, check if vanilla Firefox shows it correctly.

**Comment by PeterCxy** [comment]
I believe this has been the default since 928829d3955c02985e13f3758ba2b70b3bd7877e? But in any case the disable titlebar option works just fine for me.

**Comment by CRISPYricePC** [comment]
Disabling the title bar doesn't seem to remove the title bar, it just adds more information?
My window manager is i3wm (gaps) if that helps

#### With title bar enabled:
![image](https://user-images.githubusercontent.com/16229426/130350233-16913f9c-6328-4032-9e15-75c3f7a13840.png)

#### With title bar disabled:
![image](https://user-images.githubusercontent.com/16229426/130350182-823ea57b-72e7-48d7-9761-76848c03630d.png)

**Comment by filips123** [comment]
In any case, some kind of "title bar" always has to be displayed, because it shows window close/min/max buttons and icon for Firefox menu. If window would show just the website content without any additional bar, it would be impossible to close the window using buttons and access Firefox menus.

If `drawInTitlebar` is enabled (default), it will display non-native bar with site logo and name, Firefox widget and menu icons, and window control buttons. If `drawInTitlebar` is disabled, it will show the native window title bar with site logo and name and window control buttons, as well as additional bar with Firefox widget and menu icons.

**Comment by CRISPYricePC** [comment]
> In any case, some kind of "title bar" always has to be displayed, because it shows window close/min/max buttons and icon for Firefox menu. If window would show just the website content without any additional bar, it would be impossible to close the window using buttons and access Firefox menus.

I'm not an expert in this stuff by any means, but I think the idea is that disabling the client's title bar allows the window manager to decide what to put there (usually just a standard title bar). This is especially important for tiling WMs (dwm, i3, bspwm etc.) since they don't have title bars at all, you control the window using keyboard shortcuts.

It's an edge case, and probably brings up more issues than it solves to be honest, since a way to access the icons on the top right would still be needed. Might I suggest using the <kbd>Alt</kbd> key to bring up the File-Edit-... menu and also these extra controls?

**Comment by filips123** [comment]
Yeah, maybe I could add an option to hide those icons and title bar and allow user to show them temporarily using some keyboard shortcut. It could be `Ctrl`+`Alt` so it is separate from the File-Edit-... menu.

**Comment by filips123** [comment]
I added the option to hide all toolbars in 1.1.0. However, because this is an advanced option that is probably only useful for tiling WM users and could otherwise cause problems (for example, user could accidentally disable toolbars and wouldn't know how to enable it again), I added it behind `about:config` preference.

To hide all toolbars and disable CSD:

1. Update to FirefoxPWa 1.1.0.
2. Enable `firefoxpwa.enableHidingIconBar` in `about:config` of the PWA.
3. Restart PWA.
4. In the Firefox customize page, enable title bar (which disables CSD).
5. Also open toolbars menu and disable icon bar.

You can then temporarily show them using `Ctrl`+`Alt` for tabs/icon bar and `alt` for menu bar.

**Comment by CRISPYricePC** [comment]
Very nice, quick question. How can I get to the `about:config` page from the PWA? There's no address bar

**Comment by filips123** [comment]
You can press F6 and then enter `about:config` into the popup.

**Comment by danog** [comment]
This is really neat, but I really would like this to be the default, I have to go in about:config every time I install a new PWA just to enable the Icon bar menu entry
