### ISSUE TITLE
Why not have a profile that remains synced with the normal browser?

### ISSUE THREAD

**Issue by Samisaprogrammer** [filips123/FirefoxPWA#58]
### Problem Description

This is similar to how chromium does it, except here it would still allow multiple profiles while having one synced with the normal one (to keep cookies and extensions)

### Additional Information

It's understandable if this isn't possible, so please close this if it isn't. There is no need to explain it to me.

**Comment by filips123** [comment]
Unfortunately, this is quite hard to do because of multiple reasons:

1. Currently FirefoxPWA does all modifications per profile, which is fine because that profile is only used for PWAs. If PWA and normal profiles were the same, FirefoxPWA would also need additional logic to only apply modifications when launching PWAs.
2. It would also cause problems because PWA profile needs to be configured differently from the normal profile: Widgets are placed into title bar instead of tabs bar, some settings are changed...

Because of I will close this issue. You can use Firefox Sync/Account as a workaround to sync some of the things.

**Comment by Samisaprogrammer** [comment]
How about a sort of profile "template" that can contain all the extensions and settings preconfigured, then modified to suit PWA needs?

**Comment by filips123** [comment]
That still won't solve the problem that PWA and normal profiles need different settings and configuration.

There currently is some kind of "profile template" (`INSTALL DIRECTORY/userchrome/profile`) but it is only used internally to copy all userchrome.js modifications to the PWA profile to make sure they are updated correctly.
