### ISSUE TITLE
Failed to install system integration: Failed to process and store site icon: Failed to load icon: The image format could not be determined

### ISSUE THREAD

**Issue by adrianiepure** [filips123/FirefoxPWA#69]
### Description

When trying to create a new site, I get the following error:

'Failed to install system integration: Failed to process and store site icon: Failed to load icon: The image format could not be determined'

![image](https://user-images.githubusercontent.com/44240866/139202842-11886828-c471-4b97-ae79-5d2d190631e9.png)

Please help find a solution :)

### Steps to Reproduce

1. Go to 'https://mingle-cloudidentities.eu1.inforcloudsuite.com/idp/SSO.saml2'
2. Go to 'Install current site'
3. Click on 'Install web app'

### Additional Information

It works on other websites.

### Affected Websites

* https://mingle-cloudidentities.eu1.inforcloudsuite.com/idp/SSO.saml2

### Environment

* Operating system: Windows 10
* System architecture:  x64
* FirefoxPWA extension version: 1.2.0
* FirefoxPWA native version: 1.2.0
* Firefox version: 93.0 (64-bit)

**Comment by filips123** [comment]
Because of this report, I actually discovered four bugs/problems with the program... Anyway, these problems should be fixed or at least have a workaround in [v1.2.1](https://github.com/filips123/FirefoxPWA/releases/tag/v1.2.1).

The remaining problem is that [Infor favicon](https://mingle-cloudidentities.eu1.inforcloudsuite.com/assets/images/favicon.ico) uses some format that is currently [not compatible with the `image` crate](https://github.com/image-rs/image/issues/1590). Because of this, you won't get the correct icon when installing the site, but auto-generated icon with the letter "I" (from the site name). I don't know when this will be fixed, as it depends on the `image` crate.

In the future, I also plan to improve the function for processing icons and make fallback better, but I will create another issue for that.

**Comment by adrianiepure** [comment]
Thanks for the quick fix @filips123. I can now install the site without issues.
