### ISSUE TITLE
Open (external) links in proper browser window, not in pseudo-PWA

### ISSUE THREAD

**Issue by zakius** [filips123/FirefoxPWA#8]
Currently links open in the modified window making it pretty awkward to use as an *app*, probably can be done with ContentScript injecting into website and Native APP using kind of *system* call with the URL alone to use default browser

**Comment by filips123** [comment]
Do you mean any link that is not in PWA scope or just links with `target="_blank"`? For the former, the problem with opening links in a default browser is that some websites rely on switching between origins (for example SSO login page on different domain), and because a default browser is completely independent browser, it would be hard to switch back to the PWA browser. This would mean any website with such requirements would not work. For the latter, it could work and I will probably implement an option in the future.

You can also use a custom "Open in Browser" widget (it is not added to titlebar by default but you can add it from the Customize page) to manually open the current page in a default browser.

**Comment by zakius** [comment]
I am aware that some websites are broken by design, I guess these can be worked around with exception lists if needed, and this may not be the default behavior either to not make it too confusing for less technical users (if any decide to use this extension/project)

if it's possible to access certificate data by extensions you may also automatically add exceptions to all domains covered by current cert to make it a bit more automated and break less often

**Comment by filips123** [comment]
This will be available in the next release, but disabled by default. It can be enabled using `firefoxpwa.openOutOfScopeInDefaultBrowser` in `about:config` or "Open out of scope URLs in a default browser" in Firefox settings.

When URL that is out of PWA scope is opened, it will automatically open the default system browser and close PWA window. You can add a comma-separated list of domains where you don't want this behaviour in `firefoxpwa.allowedDomains`. I probably won't provide a default list of domains because that could be too much work. However, some URLs (non HTTP(S) URLs and restricted domains), will always be kept in the PWA browser, because otherwise some functionality of Firefox could be broken (for example, you wouldn't be able to open `about:` pages or install addons from https://addons.mozilla.org).

**Comment by PeterCxy** [comment]
Another (manual) workaround for this is to use something like the "Open With" plugin and use the right-click menu to manually send those links to the main browser.
